[buildPlans.IosevkaTkog]
family = "Iosevka Tkog"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaTkog.variants.design]
two = "straight-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
capital-a = "round-top-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-q = "crossing-baseline"
capital-r = "standing-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
g = "single-storey-earless-rounded"
i = "hooky"
l = "tailed-serifed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
u = "toothless-rounded-serifless"
w = "rounded-vertical-sides-serifless"
y = "cursive-serifless"
asterisk = "hex-low"
paren = "flat-arc"
brace = "straight"
percent = "rings-continuous-slash"
micro-sign = "toothless-rounded-serifless"
lig-ltgteq = "slanted"

[buildPlans.IosevkaTkog.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTkog.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaTkog.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaTkog.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaTkog.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaTkog.namingOverride.menuNameMap.width]
6 = "SemiExtended"

[buildPlans.IosevkaTkog.ligations]
inherits = "default-calt"
enables = [
  "tildeeq",
  "minus-minus",
  "plus-plus",
  "underscore-underscore"
]
disables = [
  "llggeq"
]
